on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: "The image to use for the job"
        required: true

jobs:
  setup-node:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
