name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# env:
# DEBUG: pw:*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm i

      - name: Test
        if: ${{ matrix.os }} == "ubuntu-latest"
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          pnpm test

      - name: Unit Test
        if: ${{ matrix.os }} != "ubuntu-latest"
        run: pnpm test-unit
