name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node.yml
        with:
          runs-on: ${{ matrix.os }}
      - uses: coactions/setup-xvfb@v1
        with:
          run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node.yml
        with:
          runs-on: ubuntu-latest
      - run: pnpm run lint
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: lint fix"
